### ISSUE TITLE
Multiplayer!

### ISSUE THREAD

**Issue by Pamblam** [Pamblam/snek#49]
It would be cool to have 2 or maybe three players play at the same time using web sockets. This would be a pretty big upgrade so I'm breaking it into several smaller issues. Once this is completed we'll release it as version 2.

 1. [x] [Don't use the global snek object](https://github.com/Pamblam/snek/issues/73)
 2. [x] [Make a bot](https://github.com/Pamblam/snek/issues/74)
 3. [x] [Always show options screen](https://github.com/Pamblam/snek/issues/75)
 4. [x] [Create players form](https://github.com/Pamblam/snek/issues/80)

**Comment by Pamblam** [comment]
I may or may not get around to writing a socket server for two live players, but it's good for now.
